use crate::{NewSmartRule, RuleMatchType, TransactionType};

/// Authentic Bangladeshi ("Deshi") starter rules for daily bank & MFS transactions.
pub fn default_rules() -> Vec<NewSmartRule> {
    vec![
        // Food & Groceries
        NewSmartRule {
            id: "rule-foodpanda".into(),
            name: "Foodpanda".into(),
            keyword: "Foodpanda".into(),
            match_type: RuleMatchType::Contains,
            category_id: "food".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
        NewSmartRule {
            id: "rule-chaldal".into(),
            name: "Chaldal".into(),
            keyword: "Chaldal".into(),
            match_type: RuleMatchType::Contains,
            category_id: "food".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
        NewSmartRule {
            id: "rule-shwapno".into(),
            name: "Shwapno".into(),
            keyword: "Shwapno".into(),
            match_type: RuleMatchType::Contains,
            category_id: "food".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
        // Shopping & Lifestyle
        NewSmartRule {
            id: "rule-daraz".into(),
            name: "Daraz".into(),
            keyword: "Daraz".into(),
            match_type: RuleMatchType::Contains,
            category_id: "shopping".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
        NewSmartRule {
            id: "rule-aarong".into(),
            name: "Aarong".into(),
            keyword: "Aarong".into(),
            match_type: RuleMatchType::Contains,
            category_id: "shopping".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
        // Transport & Commute
        NewSmartRule {
            id: "rule-pathao".into(),
            name: "Pathao".into(),
            keyword: "Pathao".into(),
            match_type: RuleMatchType::Contains,
            category_id: "transport".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
        NewSmartRule {
            id: "rule-shohoz".into(),
            name: "Shohoz".into(),
            keyword: "Shohoz".into(),
            match_type: RuleMatchType::Contains,
            category_id: "transport".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
        NewSmartRule {
            id: "rule-metro-rail".into(),
            name: "Metro Rail".into(),
            keyword: "Metro Rail".into(),
            match_type: RuleMatchType::Contains,
            category_id: "transport".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
        // Mobile Recharge
        NewSmartRule {
            id: "rule-grameenphone".into(),
            name: "Grameenphone".into(),
            keyword: "Grameenphone".into(),
            match_type: RuleMatchType::Contains,
            category_id: "recharge".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
        NewSmartRule {
            id: "rule-robi".into(),
            name: "Robi".into(),
            keyword: "Robi".into(),
            match_type: RuleMatchType::Contains,
            category_id: "recharge".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
        NewSmartRule {
            id: "rule-banglalink".into(),
            name: "Banglalink".into(),
            keyword: "Banglalink".into(),
            match_type: RuleMatchType::Contains,
            category_id: "recharge".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
        NewSmartRule {
            id: "rule-skitto".into(),
            name: "Skitto".into(),
            keyword: "Skitto".into(),
            match_type: RuleMatchType::Contains,
            category_id: "recharge".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
        // Utility Bills
        NewSmartRule {
            id: "rule-dpdc".into(),
            name: "DPDC".into(),
            keyword: "DPDC".into(),
            match_type: RuleMatchType::Contains,
            category_id: "bills".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
        NewSmartRule {
            id: "rule-desco".into(),
            name: "DESCO".into(),
            keyword: "DESCO".into(),
            match_type: RuleMatchType::Contains,
            category_id: "bills".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
        NewSmartRule {
            id: "rule-wasa".into(),
            name: "Dhaka WASA".into(),
            keyword: "WASA".into(),
            match_type: RuleMatchType::Contains,
            category_id: "bills".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
        // Healthcare & Pharmacy
        NewSmartRule {
            id: "rule-lazz-pharma".into(),
            name: "Lazz Pharma".into(),
            keyword: "Lazz Pharma".into(),
            match_type: RuleMatchType::Contains,
            category_id: "health".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
        // Education
        NewSmartRule {
            id: "rule-10ms".into(),
            name: "10 Minute School".into(),
            keyword: "10 Minute School".into(),
            match_type: RuleMatchType::Contains,
            category_id: "education".into(),
            transaction_type: TransactionType::Expense,
            is_enabled: true,
        },
    ]
}
